config/routes.rb
  Rails.application.routes.draw do
  devise_for :users
    post 'tasks/cash' => 'tasks#cash'
    root 'tasks#index'
    resources :tasks


    get   'users/:id'   =>  'users#show'

    get 'tasks/new' => 'tasks#new'
    post 'tasks' => 'tasks#create'
    get 'users/:id' => 'users#show'
    delete 'tasks/:id' => 'tasks#destroy'
    get 'tasks/:id/edit' => 'tasks#edit'
    patch 'tasks/:id'  => 'tasks#update'
    get 'tasks/:id' => 'tasks#show'
  end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
belongs_to :user
belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys:[:email]
  has_many :tasks
  belongs_to :group

  attr_accessor :group_key

  before_validation :group_key_to_id

  def group_key_to_id
    group = Group.where(name: group_key).first
    self.group_id = group.id
  end

  validate :domain_check

  def domain_check
    sql = "select domain from groups where name='#{group_key}'"
    domain=ActiveRecord::Base.connection.select_all(sql).rows.join
      unless /#{domain}/ === email
        errors[:base] << "学校のemailを登録してください"
      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:group_key])
    devise_parameter_sanitizer.permit(:sign_in, keys:[:group_key])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = current_user.group.tasks
  end

  def new
  end

  def create
    Task.create(task_params)
  end

  def show
    @task = Task.find(params[:id])
    @price = @task.price
  end

  def cash
  @amount = 500
  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )


  ###この操作で、決済をします
  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

  redirect_to  root_path
  end

private

def task_params
  params.permit(:trade, :goods, :name, :where, :when, :price, :about, :user_id, :group_id)
end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
    def show
      @user = User.find(params[:id])
      @tasks = Task.where(user_id: @user.id).page(params[:page]).per(5).order("created_at DESC")
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<header class="header">
  <div class="header__bar row">
    <h1 class="grid-5"><a class="top" href="/">PicTask</a></h1>

    <% if user_signed_in? %>
      <div class="user_nav grid-6">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        <a class="post" href="/tasks/new">投稿する</a>
      </div>
    <% else %>
      <div class="grid-6">
        <%= link_to "ログイン", new_user_session_path %>
        <%= link_to "新規登録", new_user_registration_path%>
      </div>
    <% end %>
  </div>
</header>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>

app/views/tasks/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/tasks">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tasks/index.html.erb
<section id="slide">
        <h2>
        近くにいる友達、同僚に、助けをお願い出来る掲示板サービス"Pictask"<br>
緊急な依頼（財布忘れた！過去問欲しい！等）にぜひご活用下さい
        </h2>
    </section>


    <section id="cont_2">
      <div class="title_area">
        <div class="inner_title">
            </div>
    </div>

            <div class="contents_area">
              <div class="inner_contents">
              <div class="inner_picture">
                  <span class="inner_pic"><%= image_tag 'img_04.png', width: "320" , height: "320" %> </span>
                  <span><%= image_tag 'img_06.png', width: "320" , height: "320" %> </span>
                </div>
                </div>
            </div>
    </section>

    <section id="cont_3">
      <div class="title_area">
        <div class="inner_title">
        <h2>
        売りたいもの＆買いたいもの<br>
        </h2>
        <div class="task_contents clearfix">
          <% @tasks.each do |task| %>
            <%= link_to(task_path(task.id), class: 'task_content') do%>
              <div class="task_content">
                <span>名前：<%= task.name%></span>
                <span class="time">日時：<%= task.when%></span><br />
                <span>商品名：<%= task.goods%></span>
                <span class="place">受取場所：<%= task.where%></span>
                <span class ="trade2"><%= task.trade%></span>
                <span class ="show">価格：<%= task.price%>円</span>
               </div>
            <% end%>
          <% end %>
        </div>

    <footer>
      <section id="cont_4">
        <div class="title_area">
          <div class="inner_title">
            <h3 class="mb10"><%= image_tag 'title_04.png', width: "245" , height: "19",alt: "みんははじめているよ！" %>
          </div>
        </div>
    </footer>

app/views/tasks/new.html.erb
<div class="contents row">
  <%= form_tag('/tasks', method: :post) do %>
  <%= hidden_field_tag(:user_id, current_user.id) %>
  <%= hidden_field_tag(:group_id, current_user.group.id) %>
  <h3>
      投稿する
    </h3>
    <input placeholder="買うor売るor借りる" type="text" name="trade">
    <input placeholder="商品名" type="text" name="goods">
    <input placeholder="名前" type="text" name="name">
    <input placeholder="受取場所" type="text" name="where">
    <input placeholder="日時" type="text" name="when">
    <input placeholder="価格" type="text" name="price">
    <textarea cols="30" name="about" placeholder="詳細" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class ="contents row">
    <% if user_signed_in? && current_user.id == @task.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/tasks/#{@task.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tasks/#{@task.id}", method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <div class="fomat">
      <p>名前：<%= @task.name%></p>
      <p>商品名：<%= @task.goods%></p>
      <p>受取場所：<%= @task.where%></p>
      <p>日時：<%= @task.when%></p>
      <p><%= @task.about%></p>
    <span class="name">
      <a href="/users/<%= @task.user.id %>">
        <span>投稿者</span><%= @task.user.nickname %>
      </a>
<%= form_tag tasks_cash_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>価格: <%=@task.price%>円</span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%=@price%>"
          data-locale="auto"></script>
<% end %>
</div>
    </span>
</div>

app/views/users/show.html.erb
  <div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @tasks.each do |task| %>
      <div class="content_post" style=
        <%= simple_format(task.about) %>
        <span class="name"><%= task.name %></span>
      </div>
    <% end %>
    <%= paginate(@tasks) %>
  </div>